import re


# Obvious ASR corrections from our current test recording.
# Keep this dictionary conservative.
KNOWN_CORRECTIONS = {
    "flim": "phlegm",
    "Bethescope": "stethoscope",
    "bethescope": "stethoscope",
    "That's of valid concerns": "That's a valid concern",
}


def normalize_whitespace(text: str) -> str:
    """
    Normalize repeated whitespace while preserving the text itself.
    """

    text = re.sub(r"\s+", " ", text)

    return text.strip()


def apply_known_corrections(text: str) -> str:
    """
    Apply only known, high-confidence ASR corrections.
    """

    corrected_text = text

    for incorrect, correct in KNOWN_CORRECTIONS.items():
        corrected_text = corrected_text.replace(
            incorrect,
            correct,
        )

    return corrected_text


def is_sound_event(text: str) -> bool:
    """
    Detect obvious sound-event annotations generated by ASR.
    """

    sound_event_patterns = [
        r"^sound of ",
        r"^sounds of ",
        r"^\[.*sound.*\]$",
        r"^\(.*sound.*\)$",
    ]

    normalized = text.strip().lower()

    return any(
        re.match(pattern, normalized)
        for pattern in sound_event_patterns
    )


def preprocess_segment(segment: dict) -> dict:
    """
    Clean one speaker-attributed transcript segment.
    """

    original_text = segment["text"]

    text = normalize_whitespace(original_text)

    text = apply_known_corrections(text)

    result = {
        "id": segment["id"],
        "start": segment["start"],
        "end": segment["end"],
        "speaker": segment["speaker"],
        "text": text,
    }

    if is_sound_event(text):
        result["type"] = "sound_event"
    else:
        result["type"] = "speech"

    return result


def preprocess_transcript(segments: list[dict]) -> list[dict]:
    """
    Preprocess all transcript segments.
    """

    processed_segments = []

    for segment in segments:
        processed_segment = preprocess_segment(segment)

        processed_segments.append(processed_segment)

    return processed_segments

def merge_consecutive_speaker_segments(
    segments: list[dict],
) -> list[dict]:
    """
    Merge consecutive speech segments from the same speaker.

    Sound events are kept separate.
    """

    if not segments:
        return []

    merged = []

    for segment in segments:

        # Always keep sound events separate.
        if segment["type"] == "sound_event":
            merged.append(segment)
            continue

        if not merged:
            merged.append(segment)
            continue

        previous = merged[-1]

        # Do not merge with a sound event.
        if previous["type"] == "sound_event":
            merged.append(segment)
            continue

        # Merge only when the speaker is the same.
        if (
            previous["speaker"] == segment["speaker"]
        ):
            previous["end"] = segment["end"]

            previous["text"] = (
                previous["text"].rstrip()
                + " "
                + segment["text"].lstrip()
            )

        else:
            merged.append(segment)

    return merged

def build_clean_transcript(
    segments: list[dict],
) -> list[dict]:
    """
    Complete transcript preprocessing pipeline.
    """

    processed_segments = preprocess_transcript(
        segments
    )

    merged_segments = merge_consecutive_speaker_segments(
        processed_segments
    )

    return merged_segments